### ISSUE TITLE
Lift Subsystem

### ISSUE THREAD

**Issue by aidan-lincicum** [core2062/CORE2019#1]
- Move the lift on the robot to various different positions

**Comment by sean-mcguire** [comment]
# Notes
Create and set top and bottom height limit CORE Constants in ticks from height calculations. [Make two constants]
Create and set six constants of where the six heights of the rocket are, in ticks. [Six constants]
Use a limit switch to determine the bottom of the lift and to set the encoders at 0.
Use an encoder to determine height and distance from desired height.
Check desired height against the top height limit and bottom height limit.
Run motor to move to desired lift position if less than top and more than bottom height limits.

# Function:
Limit switch sensor to configure the encoders.
Move to specified height using PID.
Manual lift movement.

**Comment by Julia-Pockat** [comment]
Got the initial code ready for testing.
