### ISSUE TITLE
Cargo Intake Subsytem

### ISSUE THREAD

**Issue by aidan-lincicum** [core2062/CORE2019#2]
- Intake cargo into mechanism

- Outtake cargo into cargo hold

**Comment by sean-mcguire** [comment]
# Notes
Ground Pickup:
Run motors to rotate wheels to grab cargo.
Sense when cargo is secure.
Stop motor intake.
Run motor to lift the intake.
Run motor to outtake cargo.
Run motor to put the intake down.

# Functions:
Moving intake wheels
Sense when cargo is in intake.
