### ISSUE TITLE
Hatch Intake Subsystem

### ISSUE THREAD

**Issue by aidan-lincicum** [core2062/CORE2019#3]
- Intake hatches to be transferred to the hatch scorer

- Outtake hatches onto ground

- Lift hatches from the horizontal position to the vertical one

**Comment by sean-mcguire** [comment]
# Notes:
Ground Pickup: 
Trigger pneumatics to push the manipulator down to horizontal position.
Run motors to spin intake wheels.
Sensor determines when to stop motor intake.
Stop intake wheels.
Trigger pneumatics to pull the manipulator and hatch to the vertical position.
Run motor to expand claw.
Rotate intake wheels while hatch scorer subsystem lifts up.

# Functions:
Pneumatic the manipulator down/up.
Spin intake wheels.
Sense when hatch is in.

**Comment by sean-mcguire** [comment]
Feeder Pickup:
Run a motor to move the claw to feeder height.
Run a motor to move claw forward.
Run a motor to expand claw.
Run a motor to move claw backward.
