### ISSUE TITLE
Hatch Scorer Subsystem

### ISSUE THREAD

**Issue by aidan-lincicum** [core2062/CORE2019#4]
- Take the hatches from the hatch intake and secure them

- Release the hatches when ready to be scored

**Comment by sean-mcguire** [comment]
# Notes:
## Feeder Pickup:
Lift to feeder height.
Close claw
Trigger a pneumatic to move the claw forward.
Run a motor to expand claw.
Pneumatic backward.

## Hatch Score
Run lift upward.
Pneumatic the hatch and claw forward to the hook tape.
Run motor to close claw.
Pneumatic to retract claw.
Lift downward.

# Function:
Actuate claw.
Flip flap.

**Comment by Julia-Pockat** [comment]
Have code that is ready to test when we get a robot.
